2025-06-16 13:52:38,367 | INFO | ðŸš€ Logger initialized at logs\robo_logger_2025-06-16_13-52-38.log
2025-06-16 13:52:38,367 | ERROR | Error training LinearRegression: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:50,367 | ERROR | Error training DecisionTreeRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:51,578 | ERROR | Error training RandomForestRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:51,656 | ERROR | Error training KNeighborsRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:51,852 | ERROR | Error training SVR: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:52,262 | ERROR | Error training GradientBoostingRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:53,703 | ERROR | Error training XGBoostRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:52:55,360 | ERROR | Error training LightGBMRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:53:06,542 | ERROR | Error training CatBoostRegressor: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 180, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 55, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
